const { CohereClient } = require("cohere-ai");
require("dotenv").config();

// Initialize Cohere client
const cohere = new CohereClient({
  token: process.env.COHERE_API_KEY,
});

const getChatbotResponse = async (message, token) => {
  try {
    console.log("Message received:", message);
    console.log("Token provided:", !!token);
    
    if (!process.env.COHERE_API_KEY) {
      throw new Error("Cohere API key is not configured");
    }
    
    if (!message || message.trim() === "") {
      throw new Error("Message cannot be empty");
    }

    // Correct Cohere API format
    const payload = {
      model: "command-light", // Use command-light for better reliability
      message: message,
      max_tokens: 500,
      temperature: 0.7,
      chat_history: [], // Empty for single messages
      preamble: "You are a helpful assistant.", // This is how you set system prompt in Cohere
    };

    console.log("Payload sent to Cohere Chat API:", payload);

    // Call the Cohere Chat API with correct format
    const response = await cohere.chat(payload);

    console.log("Cohere Chat API Response:", response);

    // Cohere returns 'text' not 'reply'
    if (!response.text) {
      throw new Error("No response generated by Cohere API");
    }

    const reply = response.text.trim();
    console.log("Generated reply:", reply);
    return reply;
    
  } catch (error) {
    console.error("Cohere API error:", error);
    console.error("Error details:", {
      name: error.name,
      message: error.message,
      status: error.status,
      body: error.body
    });
    throw new Error(`Cohere API error: ${error.message}`);
  }
};

module.exports = getChatbotResponse;